name: Build Image

on:
  push:
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: stage3-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: ./build.sh
      - name: Inspect image
        run: docker image inspect "${ORG}/${TARGET/-/:}"
      - name: Inspect portage
        run: docker run --rm "${ORG}/${TARGET/-/:}" emerge --info
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push image
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: docker push "ghcr.io/${GITHUB_REPOSITORY_OWNER}/gentoo-docker-images:${TARGET}"
